# Generated by Django 4.0 on 2021-12-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evento_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='local',
            new_name='local_evento',
        ),
    ]
